---

# Unified Role Based Playbook To Make Things Easier

- name: Modify servers to pull from correct repos
  hosts: all

  tasks:
  - name: Enable Open-Three-Tier Repo
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: "Configure High Availablity Proxy Server"
  hosts: frontends
  roles:
    - { role: haproxy_setup }

- name: "Deploy Tomcat to Servers"
  hosts: apps
  roles:
    - { role: tomcat_setup }

- name: "Deploy Postgres to Servers"
  hosts: appdbs
  roles:
    - { role: postgres_setup }

- name: "Deploy Apache to Servers"
  hosts: apps
  roles:
    - { role: apache_setup }
