---

# Unified Role Based Playbook To Make Things Easier

- name: Modify servers to pull from correct repos
  hosts: all
  gather_facts: false # remove later! speeds up testing

  tasks:
  - name: Enable Open-Three-Tier Repo
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: "Configure High Availablity Proxy Server"
  hosts: frontends
  gather_facts: false
  roles:
    - {role: ../roles/haproxy_setup}

- name: "Deploy Tomcat to Servers"
  hosts: apps
  gather_facts: true
  roles:
    - {role: ../roles/tomcat_setup}