---
- name: Install Required Packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    # - httpie
    - haproxy
    - wget
    - curl

- name: Enable HAProxy Start At Boot
  service:
    name: haproxy
    enabled: yes

- name: Adjust HAProxy Configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart_haproxy